# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

# TODO: Disable CircleCI builds

version: 2

jobs:
  unit-test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: make unit-test
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  checks-test:
    jobs:
      - unit-test
