# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

version: 2

jobs:
  checks:
    docker:
      - image: golangci/golangci-lint
    steps:
      - checkout
      - run: make checks
      - run: golangci-lint run
  unit-test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: make unit-test
      - run: bash <(curl -s https://codecov.io/bash)
  bdd-test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: make bdd-test
workflows:
  version: 2
  checks-test:
    jobs:
      - checks
      - unit-test
      - bdd-test
